export type IconOrigin = 'lucide' | 'agala'
export type IconCategory = 'actions' | 'navigation' | 'status' | 'content' | 'commerce' | 'healthcare' | 'system'

export interface IconCatalogEntry {
  name: string
  category: IconCategory
  origin: IconOrigin
  aliases?: readonly string[]
  motion?: 'spin' | 'rotate' | 'ring' | 'nudge' | 'lift'
}

export const iconCatalog = [
  { name: 'search', category: 'actions', origin: 'lucide' },
  { name: 'mail', category: 'content', origin: 'lucide' },
  { name: 'eye', category: 'actions', origin: 'lucide' },
  { name: 'eye-off', category: 'actions', origin: 'lucide' },
  { name: 'user', category: 'system', origin: 'lucide' },
  { name: 'users', category: 'system', origin: 'lucide' },
  { name: 'user-plus', category: 'system', origin: 'lucide' },
  { name: 'flag', category: 'status', origin: 'lucide' },
  { name: 'chevron-down', category: 'navigation', origin: 'lucide', aliases: ['chevron'], motion: 'rotate' },
  { name: 'chevron-right', category: 'navigation', origin: 'lucide', motion: 'rotate' },
  { name: 'chevron-left', category: 'navigation', origin: 'lucide', motion: 'rotate' },
  { name: 'chevron-up', category: 'navigation', origin: 'lucide', motion: 'rotate' },
  { name: 'check', category: 'status', origin: 'lucide' },
  { name: 'x', category: 'actions', origin: 'lucide' },
  { name: 'calendar', category: 'content', origin: 'lucide' },
  { name: 'clock', category: 'content', origin: 'lucide' },
  { name: 'refresh', category: 'actions', origin: 'lucide', motion: 'spin' },
  { name: 'minus', category: 'actions', origin: 'lucide' },
  { name: 'check-circle', category: 'status', origin: 'lucide' },
  { name: 'alert-triangle', category: 'status', origin: 'lucide' },
  { name: 'alert-circle', category: 'status', origin: 'lucide' },
  { name: 'info', category: 'status', origin: 'lucide' },
  { name: 'more-vertical', category: 'actions', origin: 'lucide' },
  { name: 'more-horizontal', category: 'actions', origin: 'lucide' },
  { name: 'arrow-up', category: 'navigation', origin: 'lucide' },
  { name: 'arrow-down', category: 'navigation', origin: 'lucide' },
  { name: 'arrow-left-right', category: 'navigation', origin: 'lucide' },
  { name: 'trending-up', category: 'status', origin: 'lucide' },
  { name: 'trending-down', category: 'status', origin: 'lucide' },
  { name: 'home', category: 'navigation', origin: 'lucide' },
  { name: 'bell', category: 'status', origin: 'lucide', motion: 'ring' },
  { name: 'bold', category: 'content', origin: 'lucide' },
  { name: 'settings', category: 'system', origin: 'lucide' },
  { name: 'menu', category: 'navigation', origin: 'lucide' },
  { name: 'panel-left', category: 'navigation', origin: 'lucide' },
  { name: 'pencil', category: 'actions', origin: 'lucide', aliases: ['edit'] },
  { name: 'italic', category: 'content', origin: 'lucide' },
  { name: 'link', category: 'content', origin: 'lucide' },
  { name: 'external-link', category: 'navigation', origin: 'lucide', motion: 'nudge' },
  { name: 'copy', category: 'actions', origin: 'lucide' },
  { name: 'trash', category: 'actions', origin: 'lucide', motion: 'lift' },
  { name: 'plus', category: 'actions', origin: 'lucide' },
  { name: 'filter', category: 'actions', origin: 'lucide' },
  { name: 'move', category: 'actions', origin: 'lucide' },
  { name: 'save', category: 'actions', origin: 'lucide' },
  { name: 'print', category: 'actions', origin: 'lucide' },
  { name: 'upload', category: 'actions', origin: 'lucide' },
  { name: 'download', category: 'actions', origin: 'lucide' },
  { name: 'file', category: 'content', origin: 'lucide' },
  { name: 'building', category: 'system', origin: 'lucide' },
  { name: 'document', category: 'content', origin: 'lucide' },
  { name: 'credit-card', category: 'commerce', origin: 'lucide' },
  { name: 'lock', category: 'system', origin: 'lucide' },
  { name: 'sign-out', category: 'system', origin: 'lucide' },
  { name: 'chart-bar', category: 'content', origin: 'lucide' },
  { name: 'archive', category: 'content', origin: 'lucide' },
  { name: 'inbox', category: 'content', origin: 'lucide' },
  { name: 'key', category: 'system', origin: 'lucide' },
  { name: 'grid', category: 'content', origin: 'lucide' },
  { name: 'columns', category: 'content', origin: 'lucide' },
  { name: 'list', category: 'content', origin: 'lucide' },
  { name: 'list-ordered', category: 'content', origin: 'lucide' },
  { name: 'spinner', category: 'status', origin: 'lucide', motion: 'spin' },
  { name: 'phone', category: 'content', origin: 'lucide' },
  { name: 'map', category: 'navigation', origin: 'lucide' },
  { name: 'map-pin', category: 'system', origin: 'lucide' },
  { name: 'directions', category: 'navigation', origin: 'lucide' },
  { name: 'store', category: 'commerce', origin: 'lucide' },
  { name: 'package', category: 'commerce', origin: 'lucide' },
  { name: 'boxes', category: 'commerce', origin: 'lucide' },
  { name: 'warehouse', category: 'commerce', origin: 'lucide' },
  { name: 'barcode', category: 'commerce', origin: 'lucide' },
  { name: 'scan', category: 'commerce', origin: 'lucide' },
  { name: 'scan-barcode', category: 'commerce', origin: 'lucide' },
  { name: 'receipt-text', category: 'commerce', origin: 'lucide', aliases: ['receipt'] },
  { name: 'truck', category: 'commerce', origin: 'lucide' },
  { name: 'tags', category: 'commerce', origin: 'lucide' },
  { name: 'percent', category: 'commerce', origin: 'lucide' },
  { name: 'wallet-cards', category: 'commerce', origin: 'lucide', aliases: ['wallet'] },
  { name: 'monitor-smartphone', category: 'system', origin: 'lucide', aliases: ['terminal'] },
  { name: 'database', category: 'system', origin: 'lucide' },
  { name: 'network', category: 'system', origin: 'lucide' },
  { name: 'stethoscope', category: 'healthcare', origin: 'lucide' },
  { name: 'clipboard-medical', category: 'healthcare', origin: 'lucide' },
  { name: 'heart-pulse', category: 'healthcare', origin: 'lucide' },
  { name: 'flask-conical', category: 'healthcare', origin: 'lucide', aliases: ['flask'] },
  { name: 'shield-plus', category: 'healthcare', origin: 'lucide' },
  { name: 'bot', category: 'system', origin: 'lucide' },
  { name: 'sparkles', category: 'status', origin: 'lucide' },
  { name: 'message-circle', category: 'content', origin: 'lucide' },
  { name: 'tooth', category: 'healthcare', origin: 'agala' },
  { name: 'odontogram', category: 'healthcare', origin: 'agala' },
  { name: 'diagnosis-link', category: 'healthcare', origin: 'agala', aliases: ['linked-diagnosis'] },
  { name: 'health-coverage', category: 'healthcare', origin: 'agala' },
  { name: 'cash-register', category: 'commerce', origin: 'agala' },
  { name: 'stock-location', category: 'commerce', origin: 'agala' },
  { name: 'price-compare', category: 'commerce', origin: 'agala' },
] as const satisfies readonly IconCatalogEntry[]

export const iconNames = iconCatalog.flatMap(entry => [
  entry.name,
  ...('aliases' in entry ? entry.aliases : []),
])
